### ISSUE TITLE
@wilson212

### ISSUE THREAD

**Issue by bf2spy** [wilson212/BattlelogGamespyService#1]
bugreport:
@Wilson212, the codes in master\BattlelogLoginServer\Database\GamespyDatabase.cs  122 line
```
var Row = base.Query("SELECT pid FROM player WHERE upper(name) = upper(@P0)", " {Nick}");
Pid = (Row.Count == 0) ? GenerateAccountId() : Int32.Parse(Row[0]["pid"].ToString());
Console.WriteLine(Row.Count); // I add this to display the Row.Count
```
No mater whether the Pid and Name in the table "player" of the stats DB, the Row.Count allways =0
What happed?
Why not use trim() instead of upper() ?

**Comment by wilson212** [comment]
The number will always be 1 or 0, since the "name" is unique... if you wanted to get the total count of players in the database, you would want to run a query like this:

```
int count = base.ExecuteScalar<int>("SELECT count(id) FROM player");
Console.WriteLine(count);
```

**Comment by bf2spy** [comment]
@wilson212 see you agin !original this two projects
Thanks again
I understand that the new user registration function does not work
It is not allowed to enter a string "username" before it runs.
does Bartlespy.dll need to re-write a terminal to call it or use php http to call?
